name: Bug report
description: Help us improve the client
labels:
  - triage
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: 🐛 Current behavior
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔍 Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error

        You can attach screenshots by dragging and dropping, or selecting and pasting them in the text field.
    validations:
      required: true
  - type: input
    id: reproduction-links
    attributes:
      label: Reproducible link
      description: A link to a minimal reproducible example. This could be a GitHub repository, CodeSandbox, or any other online code editor.
      placeholder: e.g, github.com/company/repo
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 💭 Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: client-version
    attributes:
      label: Package version
      description: What version of the client you're experiencing the issue with.
      placeholder: e.g., KurrentDB-Client-NodeJS 1.1.2
    validations:
      required: true
  - type: input
    id: kurrentdb-version
    attributes:
      label: KurrentDB Version
      description: What version of the database you are using.
      placeholder: e.g., KurrentDB v24.10
    validations:
      required: true
  - type: input
    id: connection
    attributes:
      label: Connection string
      description: What connection string you're using. Hide and sensitive information if necessary.
      placeholder: e.g., kurrentdb://admin:changeit@localhost:2113
    validations:
      required: true
  - type: dropdown
    id: deployment-environment
    attributes:
      label: ☁️ Deployment Environment
      description: How is KurrentDB deployed?
      options:
        - Single-node (Docker)
        - Single-node (Bare metal/VM)
        - Multi-node cluster (On-prem)
        - Multi-node cluster (Cloud)
        - Managed KurrentDB Cloud
        - Other (please specify below)
    validations:
      required: true
  - type: input
    id: deployment-other
    attributes:
      label: Other Deployment Details
      description: If you selected "Other," please specify your deployment setup.
      placeholder: e.g., Kubernetes with custom networking
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g., macOS 13.1
